ConroleDeEstoque/Controllers/CadastroController.cs
using ControleDeEstoque.Models;
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class CadastroController : Controller
    {

        private static List<GrupoProdutoModel> _listagrupoProduto = new List<GrupoProdutoModel>(){
            new GrupoProdutoModel() {Id=1, Nome="mouse", Ativo=true},
            new GrupoProdutoModel() {Id=2, Nome="livro", Ativo=false },
            new GrupoProdutoModel() {Id=3, Nome="teclado", Ativo=true }
        };


// GET: Cadastro
//Authorize só quem tem permissão pode acessar
        [Authorize]
        public ActionResult GrupoProduto()
        {
            return View(_listagrupoProduto);
        }

        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult LocalProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }

        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }

        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }

        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }

        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }

        [Authorize]
        public ActionResult Fornecedor()
        {
            return View();
        }

        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }

        [Authorize]
        public ActionResult Usuario()
        {
            return View();
        }
    }
}

ConroleDeEstoque/Controllers/ContaController.cs
using ConroleDeEstoque.Models;
using ControleDeEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleDeEstoque.Controllers
{
    public class ContaController : Controller
    {
        #region guarda url que o usuario tentou acessar antes do login
        //guarda a url de onde o usuario tentou acessar na variavel returnurl
        //AllowAnonymous permite qualquer um que não seja anonimo possa acessar
        [AllowAnonymous]
        public ActionResult Login(String returnUrl)
        {
            //guarda na viewbag e assim que  usuario for logado ele ser redirecionado a pagina que havia tentado acessar antes de logar
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        #endregion


        #region valida dados de login
        //verifica se os dados de login estão corretos caso não mostra a tela de login novamente
        //HttpPost para identificar qual é post
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel Login, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(Login);
            }

            //exeplo de usuario cadastrado
            var achou = UsuarioModel.ValidarUsuario(Login.Usuario, Login.Senha);

            /*
             * se usuario for cadastrado gera o cookie de autenticação do usuario usando o formsauthentication**/
            if (achou)
            {
                FormsAuthentication.SetAuthCookie(Login.Usuario, Login.LembrarMe);
                //verifica se a url que o usuario tentou acessar antes de fazer login existe 
                if (Url.IsLocalUrl(returnUrl))
                {
                    //se a url existir redireciona a url que o usuario tentou acessar
                    return Redirect(returnUrl);
                }
                else
                {
                    //se a url não existir redireciona par pagina Home
                    RedirectToAction("Index", "Home");
                }
            }
            else
            {
                //se o login nao for valido da um alerta
                ModelState.AddModelError("", "Login Invalido");
            }

            return View(Login);
        }
        #endregion


        #region logOut
        //desconectar ogin
        [HttpPost]
        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        #endregion

    }
}

ConroleDeEstoque/Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult InventarioEstoque()
        {
            return View();
        }
    }
}

ConroleDeEstoque/Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleDeEstoque.Controllers
{
    public class OperacaoController : Controller
    {
        // GET: Operacao
        [Authorize]
        public ActionResult EntradaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult SaidaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult InventarioEstoque()
        {
            return View();
        }
    }
}

ConroleDeEstoque/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*limitando a visão de quem não Fez login=============================*@
                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Cadastros
                                <span class="caret">
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Grupos de Produtos", "GrupoProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Marcas de Produtos", "MarcaProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("locais de Armazenamento", "LocalProduto", "Cadastro")</li>
                                <li>@Html.ActionLink("Unidades de Medidas", "UnidadeMedida", "Cadastro")</li>
                                <li>@Html.ActionLink("Produtos", "Produto", "Cadastro")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Paises", "Pais", "Cadastro")</li>
                                <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                                <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                                <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                                <li class="nav-divider"></li>
                                <li>@Html.ActionLink("Perfis de Usuarios", "PerfilUsuario", "Cadastro")</li>
                                <li>@Html.ActionLink("Usuarios", "Usuario", "Cadastro")</li>
                            </ul>
                        </li>


                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Operações  <span class="caret">
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Entrada de Produtos", "EntradaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Saida de Produtos", "SaidaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Lanaçamento de Perdas de Produtos", "LancPerdaProduto", "Operacao")</li>
                                <li>@Html.ActionLink("Inventário de Estoque", "InventarioEstoque", "Operacao")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Relatórios  <span class="caret">
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                                <li>@Html.ActionLink("Ressuprimentos", "Ressuprimento", "Relatorio")</li>
                            </ul>
                        </li>

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Gráficos  <span class="caret">
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Lançamento de Perdas de Produtos", "LancPerdaProduto", "Grafico")</li>
                                <li>@Html.ActionLink("Inventário de Estoque", "InventarioEstoque", "Grafico")</li>
                            </ul>
                        </li>

                    </ul>
                    using (Html.BeginForm("LogOff", "Conta", FormMethod.Post, new { id = "LogoffForm" }))
                    {

                        <ul class="nav navbar-nav navbar-right">

                            <li>@Html.ActionLink("Sobre", "Sobre", "Home")</li>
                            <li><a href="#">Ola @User.Identity.Name</a></li>
                            <li><a href="javascript:document.getElementById('LogoffForm').submit()">Sair</a></li>

                        </ul>

                    }
                    @*fim do if (Request.IsAuthenticated)=====================*@
                }


                else
                {
                    <ul class="nav navbar-nav navbar-right">

                        <li>@Html.ActionLink("Login", "Login", "Conta")</li>

                    </ul>

                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>